"use client";

import { motion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function HowItWorksPage() {
  const containerRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"]
  });



  const steps = [
    {
      id: "01",
      title: "Embed the Tracer",
      color: "bg-primary-fixed",
      textColor: "text-primary-fixed",
      desc: "AXRAY connects seamlessly to any agentic framework (LangChain, AutoGen, custom) via standard OpenTelemetry libraries. Drop in two lines of code, and you're instantly hooked into the pipeline.",
      icon: "integration_instructions",
    },
    {
      id: "02",
      title: "Span Generation",
      color: "bg-secondary-fixed",
      textColor: "text-secondary-fixed",
      desc: "As your agent loops through thoughts, tool executions, and external API requests, the tracer emits distinct, deeply-attributed spans containing prompts, context, latency, and tokens used.",
      icon: "electric_bolt",
    },
    {
      id: "03",
      title: "SigNoz Aggregation",
      color: "bg-error",
      textColor: "text-error",
      desc: "Spans are fired asynchronously to your SigNoz instance. We leverage ClickHouse under the hood to ingest millions of agent events per second with zero performance hit to your main thread.",
      icon: "database",
    },
    {
      id: "04",
      title: "AXRAY Visualizer",
      color: "bg-white",
      textColor: "text-white",
      desc: "The AXRAY dashboard pulls those traces in real-time. Instead of raw JSON, you get a frame-by-frame flight recorder UI that allows human operators to scrub through the agent's entire thought process.",
      icon: "query_stats",
    }
  ];

  return (
    <div className="min-h-screen bg-background relative selection:bg-primary-fixed selection:text-black overflow-hidden" ref={containerRef}>

      {/* Dynamic Background */}
      <div className="fixed inset-0 pointer-events-none opacity-[0.03] z-0" style={{ backgroundImage: "linear-gradient(var(--color-primary-fixed) 1px, transparent 1px), linear-gradient(90deg, var(--color-primary-fixed) 1px, transparent 1px)", backgroundSize: "64px 64px" }}></div>
      <div className="fixed inset-0 pointer-events-none bg-[radial-gradient(circle_at_center,_var(--color-background)_0%,_transparent_100%)] z-0"></div>

      {/* NotchNavBar */}
      <Navbar activePath="/how-it-works" />

      <main className="relative z-10 pt-32 pb-24">
        {/* HERO SECTION */}
        <section className="px-margin max-w-[1600px] mx-auto min-h-[60vh] flex flex-col justify-center relative items-center text-center">
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="max-w-5xl relative z-10 flex flex-col items-center"
          >
            <div className="inline-flex items-center gap-3 font-mono-label text-primary-fixed text-xs font-black uppercase tracking-[0.3em] mb-6 border-[2px] border-primary-fixed px-3 py-1 bg-primary-fixed/10">
              <div className="w-1.5 h-1.5 bg-primary-fixed animate-ping"></div>
              System Pipeline
            </div>

            <h1 className="font-headline-xl text-6xl md:text-[100px] leading-[0.9] text-white uppercase tracking-tighter font-black mb-8">
              The Anatomy <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-white to-outline-variant filter drop-shadow-[4px_4px_0px_rgba(0,0,0,1)] stroke-black" style={{ WebkitTextStroke: "2px black" }}>Of a Trace</span>
            </h1>

            <p className="font-body-md text-xl md:text-2xl text-on-surface-variant font-medium leading-relaxed max-w-2xl">
              From the first line of code generated by an agent to the final render in your browser. See exactly how data moves through the AXRAY engine.
            </p>
          </motion.div>
        </section>

        {/* PIPELINE SECTION */}
        <section className="max-w-[1200px] mx-auto px-margin relative mt-16 mb-48">

          {/* Vertical Pipeline Line */}
          <div className="absolute left-10 md:left-1/2 top-0 bottom-0 w-[4px] bg-outline-variant border-x border-black -translate-x-1/2 z-0"></div>

          <div className="space-y-24 md:space-y-32 relative z-10">
            {steps.map((step, index) => (
              <motion.div
                key={step.id}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.6 }}
                className={`flex flex-col md:flex-row md:items-center gap-8 md:gap-16 relative ${index % 2 === 0 ? 'md:flex-row' : 'md:flex-row-reverse'}`}
              >
                {/* Content Block */}
                <div className={`w-full md:w-1/2 flex flex-col pl-24 md:pl-0 ${index % 2 === 0 ? 'md:items-end md:text-right' : 'md:items-start md:text-left'} group relative z-10`}>
                  <span className={`font-mono-label text-6xl md:text-[120px] leading-none tracking-tighter opacity-10 font-black mb-2 ${step.textColor} transition-opacity duration-300 group-hover:opacity-30`}>{step.id}</span>
                  <h3 className="font-headline-xl text-3xl md:text-5xl uppercase font-black text-white mb-4">{step.title}</h3>
                  <p className="font-body-md text-on-surface-variant text-lg leading-relaxed max-w-md bg-surface-container border-[3px] border-black p-6 shadow-[6px_6px_0px_0px_#000] group-hover:-translate-y-1 transition-transform">
                    {step.desc}
                  </p>
                </div>

                {/* Center Node */}
                <div className="absolute left-10 md:left-1/2 top-4 md:top-auto -translate-x-1/2 w-12 h-12 md:w-16 md:h-16 rounded-full border-[4px] border-black bg-surface-container flex items-center justify-center z-20 shadow-[4px_4px_0px_0px_#000] group">
                  <div className={`w-full h-full rounded-full ${step.color} opacity-20 absolute inset-0 group-hover:animate-ping`}></div>
                  <span className={`material-symbols-outlined ${step.textColor} text-2xl md:text-3xl relative z-10`}>{step.icon}</span>
                </div>

                {/* Placeholder for empty side */}
                <div className="w-full md:w-1/2 hidden md:block"></div>
              </motion.div>
            ))}
          </div>

        </section>

      </main>

      {/* FOOTER */}
      <Footer />
    </div>
  );
}
