"use client";

import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background relative selection:bg-primary-fixed selection:text-black overflow-hidden">
      {/* Dynamic Background */}
      <div className="fixed inset-0 pointer-events-none opacity-[0.03] z-0" style={{ backgroundImage: "linear-gradient(var(--color-primary-fixed) 1px, transparent 1px), linear-gradient(90deg, var(--color-primary-fixed) 1px, transparent 1px)", backgroundSize: "64px 64px" }}></div>
      <div className="fixed inset-0 pointer-events-none bg-[radial-gradient(circle_at_center,_var(--color-background)_0%,_transparent_100%)] z-0"></div>

      {/* NotchNavBar */}
      <Navbar activePath="/privacy" />

      <main className="relative z-10 pt-48 pb-24 px-margin max-w-4xl mx-auto">
        <div className="inline-flex items-center gap-3 font-mono-label text-primary-fixed text-xs font-black uppercase tracking-[0.3em] mb-6 border-[2px] border-primary-fixed px-3 py-1 bg-primary-fixed/10">
          <div className="w-1.5 h-1.5 bg-primary-fixed animate-ping"></div>
          Legal Information
        </div>
        <h1 className="font-headline-xl text-5xl md:text-7xl uppercase text-white font-black mb-12 tracking-tighter">
          Privacy <span className="text-primary-fixed">Policy</span>
        </h1>
        <div className="bg-surface-container border-[4px] border-black p-8 md:p-12 shadow-[8px_8px_0px_0px_#000]">
          <div className="prose prose-invert prose-lg max-w-none font-body-md text-on-surface-variant">
            <p className="font-bold text-white mb-6">Last updated: July 22, 2026</p>
            
            <h2 className="text-primary-fixed font-black uppercase tracking-widest text-xl mt-8 mb-4 border-b-[3px] border-black pb-2 inline-block bg-black px-4 pt-2 shadow-[4px_4px_0px_0px_theme(colors.primary-fixed)]">1. Information We Collect</h2>
            <p className="mt-6 mb-8 text-lg font-medium leading-relaxed">We collect information you provide directly to us when creating an account, such as your GitHub profile metadata, email address, and authentication tokens. Additionally, we ingest telemetry trace data generated by your AI agents that you explicitly route to our OTel endpoints.</p>

            <div className="h-[3px] w-full bg-outline-variant/30 my-10"></div>

            <h2 className="text-primary-fixed font-black uppercase tracking-widest text-xl mt-8 mb-4 border-b-[3px] border-black pb-2 inline-block bg-black px-4 pt-2 shadow-[4px_4px_0px_0px_theme(colors.primary-fixed)]">2. How We Use Your Information</h2>
            <p className="mt-6 mb-8 text-lg font-medium leading-relaxed">We use collected information solely to provide, maintain, and improve AXRAY services, process transactions, authenticate sessions, and deliver real-time agent flight recorder analytics back to your dashboard.</p>

            <div className="h-[3px] w-full bg-outline-variant/30 my-10"></div>

            <h2 className="text-primary-fixed font-black uppercase tracking-widest text-xl mt-8 mb-4 border-b-[3px] border-black pb-2 inline-block bg-black px-4 pt-2 shadow-[4px_4px_0px_0px_theme(colors.primary-fixed)]">3. Data Retention & Isolation</h2>
            <p className="mt-6 mb-8 text-lg font-medium leading-relaxed">Your telemetry data is stored in tenant-isolated SigNoz and ClickHouse databases. We do not sell, rent, or trade your trace logs, prompts, or LLM completion data to any third party, nor do we use your trace data to train public AI models.</p>

            <div className="h-[3px] w-full bg-outline-variant/30 my-10"></div>

            <h2 className="text-primary-fixed font-black uppercase tracking-widest text-xl mt-8 mb-4 border-b-[3px] border-black pb-2 inline-block bg-black px-4 pt-2 shadow-[4px_4px_0px_0px_theme(colors.primary-fixed)]">4. Third-Party Access</h2>
            <p className="mt-6 mb-8 text-lg font-medium leading-relaxed">We employ minimal third-party subprocessors (like SigNoz Cloud for infrastructure). We ensure all subprocessors adhere to strict data protection standards compliant with SOC2 and GDPR.</p>
          </div>
        </div>
      </main>

      {/* FOOTER */}
      <Footer />
    </div>
  );
}
